"""add events semantic memory and queries

Revision ID: cd8ecf691b51
Revises: f4aed7e9b6a4
Create Date: 2026-10-08 18:18:52.777083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8ecf691b51'
down_revision: Union[str, Sequence[str], None] = 'f4aed7e9b6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('object_id', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('queries',
    sa.Column('query_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp_start', sa.DateTime(), nullable=False),
    sa.Column('timestamp_end', sa.DateTime(), nullable=False),
    sa.Column('best_timestamp', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('source_video', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.object_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('observations',
    sa.Column('observation_id', sa.String(length=100), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.String(length=100), nullable=True),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('frame_path', sa.Text(), nullable=True),
    sa.Column('crop_path', sa.Text(), nullable=True),
    sa.Column('source_video', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.object_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_table('semantic_memories',
    sa.Column('memory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.PrimaryKeyConstraint('memory_id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('semantic_memories')
    op.drop_table('observations')
    op.drop_table('events')
    op.drop_table('queries')
    op.drop_table('objects')
    # ### end Alembic commands ###
